# Generated by Django 4.2.6 on 2023-10-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NFLPlayer',
            fields=[
                ('uid', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('pos', models.CharField(max_length=3, verbose_name='Position')),
                ('years_played', models.CharField(blank=True, max_length=11, null=True)),
                ('fp_1970', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('fp_1971', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('fp_1972', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('fp_1973', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('fp_1974', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('fp_1975', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('fp_1976', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('fp_1977', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('fp_1978', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('fp_1979', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('fp_1980', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('fp_1981', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('fp_1982', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('fp_1983', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('fp_1984', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('fp_1985', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('fp_1986', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('fp_1987', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('fp_1988', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('fp_1989', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('fp_1990', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('fp_1991', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('fp_1992', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('fp_1993', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('fp_1994', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('fp_1995', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('fp_1996', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('fp_1997', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('fp_1998', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('fp_1999', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('fp_2000', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('fp_2001', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('fp_2002', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('fp_2003', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('fp_2004', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('fp_2005', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('fp_2006', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('fp_2007', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('fp_2008', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('fp_2009', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('fp_2010', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('fp_2011', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('fp_2012', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('fp_2013', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('fp_2014', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('fp_2015', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('fp_2016', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('fp_2017', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('fp_2018', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('fp_2019', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('fp_2020', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('fp_2021', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('fp_2022', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
            ],
        ),
    ]
