# Generated by Django 4.2.6 on 2023-10-28 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nflplayers', '0004_alter_nflplayer_fp_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nflplayer',
            name='fp_2022',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
    ]
