# Generated by Django 4.2.6 on 2023-11-19 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_nflplayer_name_searchable'),
    ]

    operations = [
        migrations.AddField(
            model_name='nflplayer',
            name='img',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
